#+SETUPFILE: src/setup.org
#+TITLE: {{fqname}}

{{desc}}

* Contents                                                         :toc_3_gh:
 - [[#about-the-project][About the project]]
     - [[#todo-overview][TODO Overview]]
     - [[#todo-status][TODO Status]]
     - [[#todo-example-usage][TODO Example usage]]
 - [[#namespaces][Namespaces]]
 - [[#tests][Tests]]
 - [[#project-definition][Project definition]]
     - [[#injected-properties][Injected properties]]
     - [[#dependencies][Dependencies]]
         - [[#runtime][Runtime]]
         - [[#development][Development]]
     - [[#leiningen-coordinates][Leiningen coordinates]]
     - [[#building-this-project][Building this project]]
         - [[#testing][Testing]]
         - [[#working-with-the-repl][Working with the REPL]]
     - [[#leiningen-project-file][Leiningen project file]]
     - [[#clojurescript-html-harness][ClojureScript HTML harness]]
     - [[#accessing-library-version-during-runtime][Accessing library version during runtime]]
         - [[#version-namespace][Version namespace]]
     - [[#release-history][Release history]]
     - [[#contributors][Contributors]]
     - [[#license][License]]

* About the project

** TODO Overview

{{desc}}

** TODO Status

ALPHA quality, in active development.

** TODO Example usage

#+BEGIN_SRC clojure
  (require '{{ns-root}}.core)

  ;; TODO some magic
#+END_SRC

* Namespaces

- [[./src/core.org][{{ns-root}}.core]]

* Tests

- [[./test/core.org][{{ns-root}}.test.core]]

* Project definition

** Injected properties                                             :noexport:

#+BEGIN_SRC clojure :exports none :noweb-ref version
0.1.0-SNAPSHOT
#+END_SRC

#+BEGIN_SRC clojure :exports none :noweb-ref project-url
{{url}}
#+END_SRC

#+BEGIN_SRC clojure :exports none :noweb yes :noweb-ref cljs-artefact-path
target/{{name}}-<<version>>.js
#+END_SRC

** Dependencies

*** Runtime

**** [[https://github.com/clojure/clojure][Clojure]]
#+BEGIN_SRC clojure :noweb-ref dep-clj
[org.clojure/clojure "1.7.0"]
#+END_SRC

**** [[https://github.com/clojure/clojurescript][ClojureScript]]
#+BEGIN_SRC clojure :noweb-ref dep-cljs
[org.clojure/clojurescript "1.7.107"]
#+END_SRC

*** Development

**** [[https://github.com/hugoduncan/criterium][Criterium]]
#+BEGIN_SRC clojure :noweb-ref dep-criterium
[criterium "0.4.3"]
#+END_SRC

**** [[https://github.com/cemerick/clojurescript.test][clojurescript.test]]
#+BEGIN_SRC clojure :noweb-ref dep-cljs-test
[com.cemerick/clojurescript.test "0.3.3"]
#+END_SRC

**** [[https://github.com/emezeske/lein-cljsbuild][Cljsbuild]]
#+BEGIN_SRC clojure :noweb-ref dep-cljsbuild
[lein-cljsbuild "1.1.0"]
#+END_SRC

** Leiningen coordinates

#+BEGIN_SRC clojure :noweb yes :noweb-ref lein-coords
  [{{fqname}} <<version>>]
#+END_SRC

** Building this project

This project is written in a literate programming format and requires
[[https://www.gnu.org/software/emacs/][Emacs]] & [[http://orgmode.org][Org-mode]] to generate usable source code. Assuming both tools
are installed, the easiest way to generate a working project is via
command line (make sure =emacs= is on your path or else edit its path
in =tangle.sh=):

#+BEGIN_SRC bash
  git clone https://github.com/{{group}}/{{name}}.git
  cd {{name}}
  ./tangle.sh src/*.org test/*.org
#+END_SRC

Tangling is the process of extracting & combining source blocks from
=.org= files into an actual working project/source tree. Once tangling
is complete, you can =cd= into the generated project directory
(={{target}}=) and then use =lein= as usual.

*** Testing

The =project.clj= file defines an alias to trigger a complete build &
tests for both CLJ & CLJS versions.

#+BEGIN_SRC bash
  cd {{target}}
  lein cleantest
#+END_SRC

To build the Clojurescript version simply run =lein cljsbuild test=
from the same directory. A small HTML harness for the resulting JS
file is also located in that folder (={{target}}/index.html=), allowing for
further experimentation in the browser.

*** Working with the REPL

Editing code blocks or files in Org-mode, then re-loading & testing
changes is quite trivial. Simply launch a REPL (via =lein= or Emacs)
as usual. Everytime you've made changes to an =.org= file, re-tangle
it from Emacs (=C-c C-v t=) or =tangle.sh=, then reload the namespace
in the REPL via =(require '{{ns-root}}... :reload)= or similar.

** Leiningen project file                                          :noexport:

#+BEGIN_SRC clojure :tangle {{tangle-target}}project.clj :noweb yes :mkdirp yes :padline no
  (defproject {{fqname}} "<<version>>"
    :description  "{{desc}}"
    :url          "<<project-url>>"
    :license      {:name "{{license-name}}"
                   :url "{{license-url}}"
                   :distribution :repo}
    :scm          {:name "git"
                   :url "https://github.com/"}

    :min-lein-vesion "2.4.0"

    :dependencies [<<dep-clj>>
                   <<dep-cljs>>]

    :profiles     {:dev {:dependencies [<<dep-criterium>>]
                         :plugins [<<dep-cljsbuild>>
                                   <<dep-cljs-test>>]
                         :global-vars {*warn-on-reflection* true}
                         :jvm-opts ^:replace []
                         :aliases {"cleantest" ["do" "clean," "test," "cljsbuild" "test"]}}}

    :cljsbuild    {:builds [{:source-paths ["src" "test"]
                             :id "dev"
                             :compiler {:output-to "<<cljs-artefact-path>>"
                                        :optimizations :whitespace
                                        :pretty-print true}}
                            {:source-paths ["src"]
                             :id "prod"
                             :compiler {:output-to "<<cljs-artefact-path>>"
                                        :optimizations :advanced
                                        :pretty-print false}}]
                   :test-commands {"unit-tests" ["phantomjs" :runner "<<cljs-artefact-path>>"]}}

    :pom-addition [:developers [:developer
                                [:name "{{author}}"]
                                [:url "{{author-url}}"]
                                [:timezone "{{tzone}}"]]])
#+END_SRC

** ClojureScript HTML harness                                      :noexport:

#+BEGIN_SRC html :tangle {{tangle-target}}index.html :noweb yes :mkdirp yes :padline no
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8">
      <title><<lein-coords>> test</title>
    </head>
    <body>
      <script type="text/javascript" src="<<cljs-artefact-path>>"></script>
    </body>
  </html>
#+END_SRC

** Accessing library version during runtime

The autogenerated namespace ={{ns-root}}.version= contains a single
symbol =version= holding the version string defined above:

#+BEGIN_SRC clojure :noweb yes
  (use '[{{ns-root}}.version])
  
  (prn version)
  ; "<<version>>"
#+END_SRC

*** Version namespace                                              :noexport:

#+BEGIN_SRC clojure :tangle {{tangle-target}}src/{{ns-root-path}}/version.cljc :noweb yes :mkdirp yes :padline no :exports none
  (ns {{ns-root}}.version)

  (def version "<<version>>")
#+END_SRC

** Release history

| *Version* | *Released* | *Description*      | *Lein coordinates*     | *Tagged Github URL* |
|-----------+------------+--------------------+------------------------+---------------------|
|     0.1.0 | pending    | 1st public release | =[{{fqname}} "0.1.0"]= |                     |

** Contributors

| *Name*     | *Role*                          | *Website*      |
|------------+---------------------------------+----------------|
| [[{{email}}][{{author}}]] | initiator & principal developer | {{author-url}} |

** License

Copyright © 2015 {{author}}

This project is open source and licensed under the [[{{license-url}}][{{license-name}}]].
